steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build 
    args: 
      - "build"
      - "-t"
      - "gcr.io/project-funky-flex/stedi:latest"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "gcr.io/project-funky-flex/stedi:latest"

  # This step deploys the dev application in kubernettes
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: Deploy
    args: 
      - run
      - --filename=stedi-dev.yaml
      - --image=gcr.io/project-funky-flex/stedi:latest
      - --location=us-east4-b
      - --output=/tmp/outputdev
      - --cluster=cluster-1


  - name: "gcr.io/cloud-builders/docker"
    id: test
    args:
      - "run"
      - "gcr.io/project-funky-flex/stedi-chikaberry"

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Production
    args:
      - 'beta'
      - 'builds'
      - 'triggers'
      - 'run'
      - '22022-07-07T16:50:20.062607910Z'
      - '--branch=main'




