#not done yet
spec:
    containers:
    - name: stedi
        image: gcr.io/cubs-consulting/stedi
        env:
        - name: REDIS_PASSWORD
            valueFrom:
            secretKeyRef:
                name: redis-secrets-dev
                key: REDIS_PASS
        - name: REDIS_HOST
            value: "redis-stedi-dev"
        - name: REDIS_PORT
            value: "6379"
        - name: REDIS_DB
            value: "0"
        - name: KAFKA_BROKER
            value: "localhost:9092"
        - name: TWILIO_ACCOUNT_SID
            valueFrom:
            secretKeyRef:
                name: twilio-dev
                key: twilio_account_sid
        - name: TWILIO_AUTH_TOKEN
            valueFrom:
            secretKeyRef:
                name: twilio-dev
                key: twilio_token
        - name: TWILIO_PHONE
            value: "+17146778438"

spec:
    containers:
    - name: stedi
        image: gcr.io/cubs-consulting/stedi
        env:
          - name: REDIS_PASSWORD
              valueFrom:
              secretKeyRef:
                  name: redis-secrets-dev
                  key: REDIS_PASS
          - name: REDIS_HOST
              value: "redis-stedi-dev"
          - name: REDIS_PORT
              value: "6379"
          - name: REDIS_DB
              value: "0"
          - name: KAFKA_BROKER
              value: "localhost:9092"
          - name: TWILIO_ACCOUNT_SID
              value: "AC76c2d08cc49098b7cd4f669656bbdb44"
          - name: TWILIO_AUTH_TOKEN
              value: "7fc613e3571bcbff53ad89bb1069e0bc"
          - name: TWILIO_PHONE
              value: "+17146778438"
---
apiVersion: v1
kind: Service
metadata:
  name: stedi
spec:
  selector:
    app: stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000